#!/bin/bash -e

if [ "`dpkg-divert --truename /usr/bin/passwd`" != /usr/sbin/real-passwd ]
then
	dpkg-divert --add --rename --divert /usr/sbin/real-passwd /usr/bin/passwd
fi

chmod u-s /usr/sbin/real-passwd

ln -s -f /usr/bin/treva-passwd /usr/bin/passwd


if [ "`dpkg-divert --truename /usr/bin/chsh`" != /usr/sbin/real-chsh ]
then
	dpkg-divert --add --rename --divert /usr/sbin/real-chsh /usr/bin/chsh
fi

chmod u-s /usr/sbin/real-chsh

ln -s -f /usr/bin/treva-chsh /usr/bin/chsh
