#!/bin/bash -e

if [ "`dpkg-divert --truename /etc/suphp/suphp.conf`" = /etc/suphp/suphp.conf.orig ]
then
	rm /etc/suphp/suphp.conf
	dpkg-divert --remove --rename /etc/suphp/suphp.conf
fi

if [ "`dpkg-divert --truename /usr/bin/chfn`" = /usr/sbin/real-chfn ]
then
	rm /usr/bin/chfn
	dpkg-divert --remove --rename /usr/bin/chfn
	chmod u+s /usr/bin/chfn
fi

