#!/bin/bash

. /usr/share/debconf/confmodule

umask 077

if [ -e /usr/share/treva-infrastructure-common/treva.pem.md5 -a "`md5sum /usr/share/treva-infrastructure-common/treva.pem`" == "`cat /usr/share/treva-infrastructure-common/treva.pem.md5`" ]; then
	exit 0
fi

md5sum /usr/share/treva-infrastructure-common/treva.pem > /usr/share/treva-infrastructure-common/treva.pem.md5

passwdfile=`mktemp`
db_get treva-infrastructure-common/ssl-password
cat <<< "$RET" | tr -d '\n' > $passwdfile
db_reset treva-infrastructure-common/ssl-password || true

while ! openssl rsa -in /usr/share/treva-infrastructure-common/treva.pem -out /etc/ssl/private/treva.pem -passin file:$passwdfile
do
	db_input critical treva-infrastructure-common/ssl-password-retry || true
	db_go
	db_get treva-infrastructure-common/ssl-password-retry
	cat <<< "$RET" | tr -d '\n' > $passwdfile
	db_reset treva-infrastructure-common/ssl-password-retry || true
done

rm -rf $passwdfile

if [ ! -n "`grep ^sslkeys /etc/group`" ]
then
	addgroup --system sslkeys
fi

openssl req -x509 -new -key /etc/ssl/private/treva.pem -out /etc/ssl/certs/treva.pem -days 3650 -batch -config /usr/share/treva-infrastructure-common/openssl.conf

chown root:sslkeys /etc/ssl/private/treva.pem
chmod 640 /etc/ssl/private/treva.pem

chown root:root /etc/ssl/certs/treva.pem
chmod 644 /etc/ssl/certs/treva.pem

chgrp sslkeys /etc/ssl/private
chmod 750 /etc/ssl/private
