#!/bin/sh -e

adduser Debian-exim sslkeys
adduser clamav Debian-exim

umask 077
mkdir -p /etc/exim4/database
touch /etc/exim4/database/{local_domains,relay_domains,local_mailboxes,local_aliases,relay_addresses,auth_passwords}
chown -R Debian-exim:Debian-exim /etc/exim4/database/

echo "ENABLED=1" >> /etc/defaults/spamassassin
echo "CRON=1" >> /etc/defaults/spamassassin
