#!/bin/bash -e

if [ ! -n "`grep ^Debian-exim: /etc/passwd`" ]
then
	adduser --system --group --home /var/spool/exim4 --no-create-home --disabled-login --force-badname Debian-exim
	adduser Debian-exim sslkeys
	adduser clamav Debian-exim
	
	/etc/init.d/clamav-daemon restart
fi

umask 077
mkdir -p /etc/exim4/database
touch /etc/exim4/database/{local_domains,relay_domains,local_mailboxes,local_aliases,local_domain_aliases,relay_addresses,auth_passwords,mailname}
chown -R Debian-exim:Debian-exim /etc/exim4/database/

echo "ENABLED=1" >> /etc/default/spamassassin
echo "CRON=1" >> /etc/default/spamassassin
/etc/init.d/spamassassin restart
